# Enable True color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# start counting at 1 for windows and panes
set -g base-index 1
set -g pane-base-index 1

# switching panes with hjkl
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind h select-pane -L

bind R source-file "~/.config/tmux/tmux.conf"

# Easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

# mouse support
set -g mouse on

# Instant switch to a new tmux session directory that exist
bind-key -r f run-shell "tmux neww ~/scripts/tmux-sessionizer"
bind-key n command-prompt "new-session -s '%%'"
bind-key C-y display-popup -d "#{pane_current_path}" -w 90% -h 90% -E "yazi" # yazi float
bind-key C-t display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "zsh" # quick floating terminal
bind-key C-g display-popup -d "#{pane-current-path}" -w 90% -h 90% -E "lazygit" # lazygit float

# Drag copy using mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# tmux plugin manager 
set -g @plugin 'tmux-plugins/tpm' # must be the first plugin

set -g @plugin 'catppuccin/tmux' # theme

set -g @plugin 'omerxx/tmux-sessionx' # default keybind "<prefix> O" to activate
set -g @plugin "tmux-plugins/tmux-resurrect" #persist tmux sessions after computer restart
set -g @plugin "tmux-plugins/tmux-continuum" #automatically save sessions every 15mins

# set -g @sessionx-bind 'o'
# set -g @resurrect-capture-pane-contents "on"
# set -g @continuum-restore "on"

set-option -g status-position top

# Configure Catppuccin
set -g @catppuccin_flavor "frappe"
set -g @catppuccin_window_status_style "rounded"

run "~/.config/tmux/plugins/tmux/catppuccin.tmux"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"

# window look and feel
set -wg automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"

set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "bg=#{@thm_bg},fg=#{@thm_rosewater}"
set -g window-status-last-style "bg=#{@thm_bg},fg=#{@thm_rosewater}"
set -g window-status-activity-style "bg=#{@thm_red},fg=#{@thm_bg}"
set -g window-status-bell-style "bg=#{@thm_red},fg=#{@thm_bg},bold"
set -gF window-status-separator "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}]│"

set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=#{@thm_blue},fg=#{@thm_bg},bold"

run '~/.config/tmux/plugins/tpm/tpm' # always keep this line last
